[package]
name = "num2words"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "num2words"
path = "src/lib.rs"


[[bin]]
name = "num2words"
path = "src/bin/bin.rs"

[dependencies]
